production:
  delivery_method: :smtp
  smtp_settings:
    enable_startttls_auto: true
    address: smtp.gmail.com
    port: 587
    domain: dealers.com
    authentication: :plain
    user_name: "onanezn45@gmail.com"
    password: "ofnanezn"

development:
  delivery_method: :smtp
  smtp_settings:
    enable_startttls_auto: true
    address: smtp.gmail.com
    port: 587
    domain: dealers.com
    authentication: :plain
    user_name: "onanezn45@gmail.com"
    password: "ofnanezn"